### ISSUE TITLE
testing the server on localhost

### ISSUE THREAD

**Issue by fabdousse** [smartytwiti/master-chat-node-angular#1]
Bonjour, quand je discute avec une autre personne sur un chat en localhost, les messages ne s'affichent pas dans la conversation. Pourtant j'ai bien allumé un serveur mongoDB et le reste indiqué dans le readme. D'où vient le problème ? 

Merci D'avance.

Fabien

**Comment by smartytwiti** [comment]
Bonsoir Fabien,

Avez vous bien configurer votre serveur mongodb sur le port 27017 (port par defaut)?
Si ceci est un vrai problem vous aurez surement des messages d'erreur, pourriez vous copier les messages d'erreur affiché dans votre console (chrome console et console de l'os) 

Marwen
Cordialement

**Comment by fabdousse** [comment]
Hi again,
I checked with the updated version on git. This issue for printing messages in a conversation still remains and  yes I think this is because there is no collection message on MongoDB.

Thank you for your help.
Fabien

**Comment by smartytwiti** [comment]
Hi Fabien,

In order to reproduce your issue, could you please give us your environment (os), node, mongodb  versions ? 

Marwen
Cheers

**Comment by fabdousse** [comment]
I am running it on Windows 7, node.js 5.5.0 and mongodb 3.0.7 :)

Fabien

**Comment by smartytwiti** [comment]
Can't reproduce this issue with the above environment. Can you zip your project and send it? I want to  check your project especially the npm modules versions..

Best regards
Marwen

**Comment by fabdousse** [comment]
I sent it to you on facebook. It didn't download here.
Thanks
Best Regards
Fabien

**Comment by fabdousse** [comment]
I solved the problem, I just changed the port in index.js and not in SocketService.js.
